<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#2.1.-Numpy-ndarray---создание" data-toc-modified-id="2.1.-Numpy-ndarray---создание-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>2.1. Numpy ndarray - создание</a></span></li><li><span><a href="#2.2.-Numpy-ndarray---индексы" data-toc-modified-id="2.2.-Numpy-ndarray---индексы-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>2.2. Numpy ndarray - индексы</a></span><ul class="toc-item"><li><span><a href="#TLDR:" data-toc-modified-id="TLDR:-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>TLDR:</a></span></li></ul></li><li><span><a href="#2.3.-Numpy-ndarray---элементарные-операции-с-массивами" data-toc-modified-id="2.3.-Numpy-ndarray---элементарные-операции-с-массивами-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>2.3. Numpy ndarray - элементарные операции с массивами</a></span><ul class="toc-item"><li><span><a href="#TLDR:" data-toc-modified-id="TLDR:-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>TLDR:</a></span></li></ul></li><li><span><a href="#2.4.-Numpy---основные-функции." data-toc-modified-id="2.4.-Numpy---основные-функции.-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>2.4. Numpy - основные функции.</a></span><ul class="toc-item"><li><span><a href="#TLDR:" data-toc-modified-id="TLDR:-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>TLDR:</a></span></li></ul></li><li><span><a href="#2.5.-Numpy---I/O." data-toc-modified-id="2.5.-Numpy---I/O.-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>2.5. Numpy - I/O.</a></span></li></ul></div>

In [1]:
%matplotlib inline
import matplotlib.pyplot as plt

# 2.1. Numpy ndarray - создание

Numpy - библиотека для векторизованных вычислений в Python'e. Написана на C. Основной объект в numpy - nddarray, который располагается напрерывно в памяти и позволяет производить быстрые вычисления.

In [2]:
import numpy as np

In [3]:
%%timeit
a = np.array(list(range(10000)))
a * a

843 µs ± 3.74 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
%%timeit
a = np.array(list(range(10000)))
a ** 2

856 µs ± 3.95 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [8]:
%%timeit
a = np.arange(10000)
a ** 2

14.5 µs ± 39.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Создание массива

In [11]:
a = np.array([1, 2, 3, 4])

In [12]:
a.shape

(4,)

Shape - кортеж, который указывает число элементов в каждом измерении. 

In [13]:
a = np.array([[1, 2], [3, 4]])

In [15]:
a

array([[1, 2],
       [3, 4]])

In [16]:
a.size

4

In [17]:
a.shape

(2, 2)

In [18]:
a.dtype

dtype('int64')

In [19]:
a.itemsize

8

In [20]:
a.nbytes

32

In [23]:
a.reshape(4, 1)

array([[1],
       [2],
       [3],
       [4]])

In [24]:
a.reshape(1, 3)

ValueError: cannot reshape array of size 4 into shape (1,3)

In [27]:
a.reshape(4, -1)

array([[1],
       [2],
       [3],
       [4]])

In [28]:
a.reshape(1, -1).shape

(1, 4)

При желании, можно использовать np.size(np.object) и np.shape(np.object):

In [29]:
np.size(a)

4

In [30]:
np.shape(a)

(2, 2)

При необходимости, не стоит принебрегать встроенной справкой:

In [ ]:
np.array()

И специальными функциями numpy:

In [33]:
np.lookfor('create list')

Search results for 'create list'
--------------------------------
numpy.ma.mrecords.fromarrays
    Creates a mrecarray from a (flat) list of masked arrays.
numpy.ma.mrecords.fromrecords
    Creates a MaskedRecords from a list of records.
numpy.core._dtype._construction_repr
    Creates a string repr of the dtype, excluding the 'dtype()' part
numpy.partition
    Return a partitioned copy of an array.
numpy.nested_iters
    Create nditers for use in nested loops
numpy.chararray.tolist
    a.tolist()
numpy.distutils.fcompiler.FCompiler._need_link
    Return true if we need to relink the files listed in 'objects'
numpy.distutils.fcompiler.FCompiler.create_static_lib
    Link a bunch of stuff together to create a static library file.
numpy.distutils.misc_util.Configuration.add_extension
    Add extension to configuration.
numpy.distutils.command.sdist.sdist.prune_file_list
    Prune off branches that might slip into the file list as created
numpy.distutils.msvccompiler.MSVCCompiler.create_s

и IPython:

In [34]:
np.sa*?

In [35]:
a

array([[1, 2],
       [3, 4]])

In [36]:
a[0, 0] = 100

In [37]:
a

array([[100,   2],
       [  3,   4]])

**Создание массивов**

Создавать из списков мы уже умеем:

In [39]:
x = [1, 2, 3, 4]

In [43]:
np.array([1, 2, 3, 4], dtype=np.int16)

array([1, 2, 3, 4], dtype=int16)

In [53]:
np.arange(100, 1000, 30)

array([100, 130, 160, 190, 220, 250, 280, 310, 340, 370, 400, 430, 460,
       490, 520, 550, 580, 610, 640, 670, 700, 730, 760, 790, 820, 850,
       880, 910, 940, 970])

In [49]:
np.linspace(0, 1, 25)

array([0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667,
       0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ,
       0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333,
       0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667,
       0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ])

In [50]:
np.linspace(0, 1, 25, endpoint=False)

array([0.  , 0.04, 0.08, 0.12, 0.16, 0.2 , 0.24, 0.28, 0.32, 0.36, 0.4 ,
       0.44, 0.48, 0.52, 0.56, 0.6 , 0.64, 0.68, 0.72, 0.76, 0.8 , 0.84,
       0.88, 0.92, 0.96])

In [51]:
np.linspace(0, 1, 26)

array([0.  , 0.04, 0.08, 0.12, 0.16, 0.2 , 0.24, 0.28, 0.32, 0.36, 0.4 ,
       0.44, 0.48, 0.52, 0.56, 0.6 , 0.64, 0.68, 0.72, 0.76, 0.8 , 0.84,
       0.88, 0.92, 0.96, 1.  ])

In [59]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [60]:
np.ones(3)

array([1., 1., 1.])

In [65]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [66]:
np.ones((3, 2), 'complex')

array([[1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j]])

In [71]:
A = np.arange(100).reshape(4, 25)

In [72]:
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [73]:
np.ones_like(A)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1]])

In [74]:
np.zeros_like(A)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0]])

In [81]:
np.diag(np.array([1, 2, 3, 4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

** Случайные массивы **

на интервале [0,1]:

In [88]:
np.random.rand(3, 2)

array([[0.84602469, 0.47332988],
       [0.90255503, 0.22599553],
       [0.30415374, 0.71499388]])

Нормально распределенные:

In [89]:
np.random.randn(3, 2)

array([[ 0.62201559, -1.6552821 ],
       [-0.20247207,  0.54174276],
       [ 0.04477872, -1.0454432 ]])

-- N: иногда полезно получить случайное целое число:

In [93]:
np.random.randint(0, 100, (10, 20)).reshape(5, -1)

array([[80, 16, 38,  7, 63, 87, 57, 50, 17, 11, 64, 27,  9, 29, 85, 75,
        26, 78, 16, 61, 87, 85, 35, 75, 63, 88, 18, 61, 38, 52, 85, 91,
        38, 93, 65, 22, 67, 71,  0, 20],
       [ 9, 84, 68, 78, 37, 81, 96, 71, 63,  5, 35, 65, 55, 16, 86, 15,
        56, 63, 74, 98, 81,  7, 90, 37, 52, 80, 10, 95, 97, 78, 65, 23,
        40, 10,  2, 45, 14, 73, 41, 78],
       [18, 81, 15,  8, 80, 71, 61, 50, 27, 11, 10, 93, 84, 27,  2, 77,
        64, 81, 14, 52, 57, 93, 76, 14, 17, 42, 57, 41, 26, 61, 81, 59,
        60, 39,  2, 58,  8, 11, 58,  4],
       [83, 66,  8, 13, 52, 39,  7, 77, 64, 93, 26,  4,  6, 21, 78, 37,
        77, 77, 92, 98, 96, 95, 62, 76, 10, 63, 24, 62, 29, 62, 83, 21,
        55, 45, 72, 43, 36, 87, 22, 79],
       [39, 13,  7, 98, 55, 54, 10, 64, 93, 34, 86,  5, 14, 26,  0, 34,
         3, 36,  8, 62, 43, 17,  8,  1, 43, 77, 93, 92, 34, 88, 77, 85,
         9,  3, 16, 96, 82, 26, 35, 17]])

In [95]:
A

array([0, 1, 2, 3, 4])

In [98]:
A = np.arange(5)
print(A)
A[[0, 1, -4]]

[0 1 2 3 4]


array([0, 1, 1])

# 2.2. Numpy ndarray - индексы

Отдельно рассмотрим 1-мерный и многомерные массивы.

In [99]:
t = np.random.rand(3,)

In [100]:
t

array([0.75166392, 0.93711056, 0.17391382])

Для одномерного массива получим сразу элемент, который находится по данному индексу. Для n-мерного массива подобная индексация вернет массив размера n-1.

In [102]:
t.shape

(3, 5, 10)

In [101]:
t = np.random.rand(3, 5, 10)
t

array([[[0.87301031, 0.00745994, 0.70710122, 0.2285698 , 0.43634349,
         0.50444539, 0.76613476, 0.72652494, 0.82703883, 0.52027174],
        [0.99381094, 0.80207809, 0.17456676, 0.04727266, 0.2783685 ,
         0.26785255, 0.42730036, 0.10656352, 0.32405288, 0.60943969],
        [0.41710009, 0.14362107, 0.27890767, 0.15011804, 0.18925033,
         0.78348583, 0.60880837, 0.02562822, 0.63840574, 0.15677252],
        [0.63551445, 0.16024329, 0.42826223, 0.8366597 , 0.4950934 ,
         0.23060009, 0.97667323, 0.54583886, 0.2244354 , 0.47488053],
        [0.32132998, 0.27954288, 0.18568009, 0.74029965, 0.80535378,
         0.3797386 , 0.27295783, 0.13978662, 0.16109638, 0.07160995]],

       [[0.63222939, 0.4656865 , 0.40979217, 0.95648762, 0.35317602,
         0.88619065, 0.72682258, 0.89215991, 0.6564955 , 0.3157901 ],
        [0.36365124, 0.24220195, 0.01486448, 0.87435808, 0.82988932,
         0.61956519, 0.32910537, 0.66052239, 0.28567328, 0.51893988],
        [0.9122064 , 0.18

In [103]:
t.shape

(3, 5, 10)

In [110]:
t[0, 1, :]

array([0.99381094, 0.80207809, 0.17456676, 0.04727266, 0.2783685 ,
       0.26785255, 0.42730036, 0.10656352, 0.32405288, 0.60943969])

In [111]:
t[0, 1, 5]

0.2678525512966716

In [114]:
np.random.rand(3, 5, 10)[1].shape

(5, 10)

In [115]:
np.random.rand(3, 5)[1].shape

(5,)

Можно использовать ':' вместо индекса:

In [116]:
A = np.random.rand(3, 5)

In [117]:
A

array([[0.13823203, 0.16540871, 0.56987822, 0.42776509, 0.46925707],
       [0.09253591, 0.44337368, 0.60560593, 0.31910961, 0.27828972],
       [0.13863822, 0.31764783, 0.73038726, 0.29603771, 0.93711262]])

In [118]:
A[0, :]

array([0.13823203, 0.16540871, 0.56987822, 0.42776509, 0.46925707])

In [119]:
A[:, 0]

array([0.13823203, 0.09253591, 0.13863822])

Поддерживается стандартный протокол - python slicing syntax ([lower:upper:step]) :

In [120]:
A[0, :]

array([0.13823203, 0.16540871, 0.56987822, 0.42776509, 0.46925707])

In [127]:
A[0, :][0:4:2]

array([0.13823203, 0.56987822])

In [124]:
a = A[0, :]

In [125]:
a

array([0.13823203, 0.16540871, 0.56987822, 0.42776509, 0.46925707])

Операция slicing создает т.н. view - то есть данные не копируются, поэтому исходный объект по адресу - mutable.

In [128]:
A[0,:][0:4:2]

array([0.13823203, 0.56987822])

In [129]:
A[0,:][0:4:2] = [1.0, 2.5]

In [131]:
A

array([[1.        , 0.16540871, 2.5       , 0.42776509, 0.46925707],
       [0.09253591, 0.44337368, 0.60560593, 0.31910961, 0.27828972],
       [0.13863822, 0.31764783, 0.73038726, 0.29603771, 0.93711262]])

Параметры для slicing могут пропускаться:

In [132]:
A[0, :][0:4:2]

array([1. , 2.5])

In [134]:
A[0, :][0:4:1]

array([1.        , 0.16540871, 2.5       , 0.42776509])

In [137]:
A[0, :][0:3]

array([1.        , 0.16540871, 2.5       ])

In [138]:
A[0, :][3:]

array([0.42776509, 0.46925707])

In [139]:
A[0, :]

array([1.        , 0.16540871, 2.5       , 0.42776509, 0.46925707])

In [140]:
A[0, :][::-1]

array([0.46925707, 0.42776509, 2.5       , 0.16540871, 1.        ])

In [141]:
A[0, :]

array([1.        , 0.16540871, 2.5       , 0.42776509, 0.46925707])

In [142]:
A[0, :][:-3]

array([1.        , 0.16540871])

In [143]:
A[0, :][-3:]

array([2.5       , 0.42776509, 0.46925707])

** Fancy Indexing **

Этим термином обозначается индексирование с помощью массивов (или иных итерируемых конструкций).

In [144]:
A

array([[1.        , 0.16540871, 2.5       , 0.42776509, 0.46925707],
       [0.09253591, 0.44337368, 0.60560593, 0.31910961, 0.27828972],
       [0.13863822, 0.31764783, 0.73038726, 0.29603771, 0.93711262]])

In [145]:
row_indices = [1, 2]
A[row_indices]

array([[0.09253591, 0.44337368, 0.60560593, 0.31910961, 0.27828972],
       [0.13863822, 0.31764783, 0.73038726, 0.29603771, 0.93711262]])

In [146]:
col_indices = [1, -1] # [1, 4]
A[row_indices, col_indices]

array([0.44337368, 0.93711262])

Возможно Булево индексирование (**Boolean indexing**):

In [148]:
B

array([0, 1, 2, 3, 4])

In [149]:
B = np.array([n for n in range(5)])
row_mask = np.array([True, False, True, False, False])
B[row_mask]

array([0, 2])

In [150]:
B > 2

array([False, False, False,  True,  True])

In [151]:
B[B > 2]

array([3, 4])

In [157]:
np.array([1, 0, 1, 0, 0], dtype=bool)

array([ True, False,  True, False, False])

In [154]:
row_mask = np.array([1, 0, 1, 0, 0], dtype=bool)
B[row_mask]

array([0, 2])

In [156]:
B

array([0, 1, 2, 3, 4])

In [158]:
row_mask = np.array([1, 0, 1, 0, 3])
B[row_mask]

array([1, 0, 1, 0, 3])

Это очень удобно, как вы наверняка догадались, если мы хотим отобрать данные, отвечающие определенным условиям:

In [159]:
x = np.arange(0, 10, 0.5)
x

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [160]:
mask = (5 < x) * (x < 7.5)
mask

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False])

In [161]:
mask = (5 < x) & (x < 7.5)
mask

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False])

In [162]:
x[mask]

array([5.5, 6. , 6.5, 7. ])

In [163]:
a = np.array([[1, 2], [3, 4]])

In [166]:
a

array([[1, 2],
       [3, 4]])

In [165]:
(a > 1)

array([[False,  True],
       [ True,  True]])

In [168]:
a[a > 2]

array([3, 4])

Получить список индексов элементов, отвечающих заданной маске, можно с помощью **where**:

In [173]:
mask

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False])

In [174]:
indices = np.where(mask)

indices

(array([11, 12, 13, 14]),)

In [175]:
x[indices]

array([5.5, 6. , 6.5, 7. ])

**take** еще одна конструкция выбора элементов массива:

In [176]:
v = np.arange(-3, 3)
row_indices = [1, 3, 5]

In [177]:
v

array([-3, -2, -1,  0,  1,  2])

In [178]:
v[row_indices]

array([-2,  0,  2])

In [179]:
v.take(row_indices)

array([-2,  0,  2])

In [180]:
np.take(v, row_indices)

array([-2,  0,  2])

## TLDR:
* для доступа к элементам массива пользуйтесь slicing и помните, что slicing создает view, а значит исходный массив может быть изменен.

# 2.3. Numpy ndarray - элементарные операции с массивами

** Broadcasting **

Концепеция broadcasting является ключевой для понимания операций с массивами. Обычно, операции с массивами производятся поэлементно. 

In [190]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])

In [191]:
a / b

array([0.5, 1. , 1.5])

Что, если массивы разного размера? Начнем с простого - скаляр и вектор:

In [193]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

Все просто - скаляр словно "вырастает" (broadcasted) до размеров вектора и производится поэлементная операция (разумеется, это умозрительная аналогия - новый вектор из 2 не создается!).

Общее правило таково:

операция может произведена если размерность "крайних" осей массивов совпадает (trailing dimension), либо один из элементов является скаляром.

Пример из оффициальной документации:

In [ ]:
'''

Image  (3d array): 256 x 256 x 3
Scale  (1d array):             3
Result (3d array): 256 x 256 x 3

A      (4d array):  8 x 1 x 6 x 1
B      (3d array):      7 x 1 x 5
Result (4d array):  8 x 7 x 6 x 5

'''
pass

In [215]:
a = np.random.randint(0, 5, (8, 1, 6, 3))

In [216]:
b = np.random.randint(0, 5, (7, 1, 5))

In [214]:
(a * b).shape

(8, 7, 6, 5)

а вот эти операции дадут вам ошибку:

In [ ]:
'''
A      (1d array):  3
B      (1d array):  4 # trailing dimensions do not match

A      (2d array):      2 x 1
B      (3d array):  8 x 4 x 3 # second from last dimensions mismatched
'''
pass

In [221]:
x

array([0, 1, 2, 3])

In [222]:
y

array([1., 1., 1., 1., 1.])

In [220]:
x = np.arange(4)
xx = x.reshape(4, 1)
y = np.ones(5)
z = np.ones((3, 4))

print(x.shape)

print(y.shape)

x + y

(4,)
(5,)


ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [223]:
y

array([1., 1., 1., 1., 1.])

In [224]:
xx

array([[0],
       [1],
       [2],
       [3]])

In [225]:
print(xx.shape)
print(y.shape)
print((xx + y).shape)
print(xx + y)

print('-------')

print(x.shape)
print(z.shape)
print((x + z).shape)
print(x + z)

(4, 1)
(5,)
(4, 5)
[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]
-------
(4,)
(3, 4)
(3, 4)
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


Классный пример из официальной документации:

In [226]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
a[:, np.newaxis] + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [229]:
a.shape

(4,)

In [230]:
a[:, np.newaxis].shape

(4, 1)

In [232]:
a[np.newaxis, :].shape

(1, 4)

In [233]:
a[np.newaxis, :]

array([[ 0., 10., 20., 30.]])

** Операции вида "массив - скаляр" **

In [234]:
A

array([[1.        , 0.16540871, 2.5       , 0.42776509, 0.46925707],
       [0.09253591, 0.44337368, 0.60560593, 0.31910961, 0.27828972],
       [0.13863822, 0.31764783, 0.73038726, 0.29603771, 0.93711262]])

In [237]:
A + 2

array([[3.        , 2.16540871, 4.5       , 2.42776509, 2.46925707],
       [2.09253591, 2.44337368, 2.60560593, 2.31910961, 2.27828972],
       [2.13863822, 2.31764783, 2.73038726, 2.29603771, 2.93711262]])

** Операции вида "массив - массив" **

Производятся поэлементно с учетом правил broadcasting:

In [238]:
A * A

array([[1.        , 0.02736004, 6.25      , 0.18298297, 0.2202022 ],
       [0.00856289, 0.19658022, 0.36675854, 0.10183094, 0.07744517],
       [0.01922056, 0.10090014, 0.53346555, 0.08763833, 0.87818006]])

In [239]:
A / A

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

** Матричные операции**

In [240]:
A = np.random.rand(3,3)

In [242]:
A

array([[0.76420585, 0.31591944, 0.2711323 ],
       [0.23702937, 0.65843584, 0.17618727],
       [0.16543585, 0.81015897, 0.07469407]])

In [241]:
np.dot(A, A)

array([[0.70374778, 0.66910043, 0.28311385],
       [0.36635556, 0.65115963, 0.19343447],
       [0.33081559, 0.64621617, 0.1931739 ]])

In [243]:
v = np.random.randn(3)

In [244]:
v

array([ 0.2368347 , -0.16631123, -1.34255206])

In [245]:
A.shape

(3, 3)

In [246]:
v[:, np.newaxis]

array([[ 0.2368347 ],
       [-0.16631123],
       [-1.34255206]])

In [249]:
A

array([[0.76420585, 0.31591944, 0.2711323 ],
       [0.23702937, 0.65843584, 0.17618727],
       [0.16543585, 0.81015897, 0.07469407]])

In [250]:
A * v

array([[ 0.18099047, -0.05254095, -0.36400923],
       [ 0.05613678, -0.10950528, -0.23654058],
       [ 0.03918095, -0.13473854, -0.10028068]])

In [251]:
np.dot(A, v)

array([-0.23555972, -0.28990907, -0.19583827])

In [253]:
v[:, np.newaxis].shape

(3, 1)

In [252]:
np.dot(A, v[:, np.newaxis])

array([[-0.23555972],
       [-0.28990907],
       [-0.19583827]])

In [254]:
A.dot(v[:, np.newaxis])

array([[-0.23555972],
       [-0.28990907],
       [-0.19583827]])

In [255]:
np.dot(v[np.newaxis, :], A)

array([[-0.08053642, -1.12236519, -0.06536906]])

In [257]:
v

array([ 0.2368347 , -0.16631123, -1.34255206])

In [256]:
np.dot(v, v)

1.8861961405632917

Если хочется использовать по умолчанию операции из матричной алгебры, то можно использовать конструктор matrix().

In [258]:
M = np.matrix(A)

In [259]:
v1 = np.matrix(v).T

In [260]:
M.shape

(3, 3)

In [263]:
v1

matrix([[ 0.2368347 ],
        [-0.16631123],
        [-1.34255206]])

In [262]:
v1.T * v1

matrix([[1.88619614]])

In [264]:
M * v1

matrix([[-0.23555972],
        [-0.28990907],
        [-0.19583827]])

** Преобразование массивов**

In [265]:
A

array([[0.76420585, 0.31591944, 0.2711323 ],
       [0.23702937, 0.65843584, 0.17618727],
       [0.16543585, 0.81015897, 0.07469407]])

In [266]:
A.T

array([[0.76420585, 0.23702937, 0.16543585],
       [0.31591944, 0.65843584, 0.81015897],
       [0.2711323 , 0.17618727, 0.07469407]])

** reshape **

In [268]:
a

array([ 0., 10., 20., 30.])

In [269]:
a = a.reshape((2, 2))

In [270]:
a

array([[ 0., 10.],
       [20., 30.]])

In [274]:
a.reshape(-1, 2)

array([[ 0., 10.],
       [20., 30.]])

** resize **

In [275]:
a = np.arange(4)

In [276]:
a

array([0, 1, 2, 3])

In [282]:
a.resize((8, ), refcheck=False)

In [283]:
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [285]:
a = np.array([[1, 2], [3, 4]])
np.repeat(a, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])

In [287]:
np.tile(a, 2)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

** concatenate **

In [288]:
a

array([[1, 2],
       [3, 4]])

In [293]:
b = np.array([[5, 6]])

In [296]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [299]:
b

array([[5, 6]])

In [298]:
b.T

array([[5],
       [6]])

In [301]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

** hstack **

Название говорит само за себя - horizontal stack.

In [302]:
np.hstack((a, b.T))

array([[1, 2, 5],
       [3, 4, 6]])

In [303]:
a.shape

(2, 2)

In [304]:
b.T.shape

(2, 1)

** vstack **

In [305]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [306]:
a.shape

(2, 2)

In [307]:
b.shape

(1, 2)

** Копии и view **

Мы помним, что очень важно различать копирование объекта и присваивание новой ссылки на объект. Numpy в этом смысле не отличается от списков:

In [308]:
A = np.array([[1, 2], [3, 4]])

In [310]:
B = A

In [311]:
B[0, 0] = 10

In [312]:
A

array([[10,  2],
       [ 3,  4]])

Если это не тот тип поведения, который нам нужен - следует использовать np.copy():

In [313]:
A = np.array([[1, 2], [3, 4]])

In [314]:
B = np.copy(A)

In [315]:
B[0, 0] = 100

In [316]:
A

array([[1, 2],
       [3, 4]])

Важно помнить, что если вы используете view массива, то копии вы не создаете!

In [323]:
a = np.arange(10)

In [324]:
b = a[:]

In [325]:
np.may_share_memory(a, b)

True

In [320]:
c = a[::2].copy()
np.may_share_memory(a, c)

False

In [326]:
d = a.T
np.may_share_memory(a, d)

True

In [327]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [328]:
b[0] = -11

In [329]:
a

array([-11,   1,   2,   3,   4,   5,   6,   7,   8,   9])

## TLDR:
* следует отличать копию массива и view;
* при осуществлении операций помните про правила broadcasting;
* запомните hstack и vstack.

# 2.4. Numpy - основные функции.

** Встроенные функции массива **

In [330]:
m = np.random.randint(0, 10, (3, 3))

In [331]:
m

array([[1, 4, 9],
       [2, 3, 1],
       [0, 7, 6]])

In [332]:
m.sum()

33

In [333]:
m.max()

9

In [334]:
m.min()

0

** Всегда используйте встроенные функции! **

In [336]:
a = np.random.rand(1000)

In [337]:
%timeit -n 1000 max(a)

92.5 µs ± 1.41 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [338]:
%timeit -n 1000 a.max()

3.4 µs ± 912 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [339]:
%timeit -n 1000 sum(a)

161 µs ± 1.07 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [340]:
%timeit -n 1000 a.sum()

3.38 µs ± 1.03 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Просто считать сумму элементов матрицы или находить максимальный элемент не так интересно, и тут нам помогают axis:

In [341]:
m

array([[1, 4, 9],
       [2, 3, 1],
       [0, 7, 6]])

In [342]:
m.sum(axis=0)

array([ 3, 14, 16])

In [343]:
m.sum(axis=1)

array([14,  6, 13])

In [344]:
m.max(axis=0)

array([2, 7, 9])

Очень полезно произведение всех элементов:

In [345]:
m.prod(axis=1)

array([36,  6,  0])

Кумулятивная сумма элементов:

In [346]:
m.cumsum()

array([ 1,  5, 14, 16, 19, 20, 20, 27, 33])

Кумулятивное произведение:

In [348]:
m.cumprod()

array([  1,   4,  36,  72, 216, 216,   0,   0,   0])

**Простые статистики**

**Среднее**

In [351]:
m

array([[1, 4, 9],
       [2, 3, 1],
       [0, 7, 6]])

In [349]:
m.mean(axis=0)

array([1.        , 4.66666667, 5.33333333])

In [353]:
np.mean(m, axis=1)

array([4.66666667, 2.        , 4.33333333])

In [356]:
np.mean(m)

3.6666666666666665

In [358]:
m.mean()

3.6666666666666665

**Медиана**

In [359]:
np.median(m, axis=0)

array([1., 4., 6.])

In [361]:
np.median(m)

3.0

** Дисперсия **

In [362]:
np.std(m, axis=0)

array([0.81649658, 1.69967317, 3.29983165])

In [363]:
m.std(axis=0)

array([0.81649658, 1.69967317, 3.29983165])

In [364]:
np.var(a)

0.08180522085385115

In [365]:
a.var()

0.08180522085385115

** Сортировка **

In [368]:
a = np.random.randint(0, 100, 12)

In [369]:
a

array([36, 63, 77, 78,  5, 10, 25, 80,  8, 67, 41, 65])

In [372]:
np.sort(a)[::-1]

array([80, 78, 77, 67, 65, 63, 41, 36, 25, 10,  8,  5])

Функция выше возвращает отсортированную копию массива. Если нужна сортировка in-place:

In [379]:
a = np.random.randint(0, 100, 12)

In [382]:
a = np.sort(a)

In [377]:
a.sort()

In [384]:
a

array([ 4, 12, 22, 24, 28, 59, 67, 69, 79, 81, 82, 97])

In [386]:
a = np.random.rand(100)

In [397]:
a = np.random.randint(0, 100, 120)

In [389]:
a

array([11, 16, 43, 76, 98, 36, 81,  8, 85, 10, 35, 15])

Также иногда бывает полезно получить только список индексов в правильном порядке:

In [390]:
np.argsort(a)

array([ 7,  9,  0, 11,  1, 10,  5,  2,  3,  6,  8,  4])

In [391]:
a[np.argsort(a)]

array([ 8, 10, 11, 15, 16, 35, 36, 43, 76, 81, 85, 98])

In [394]:
np.argmax(a)

4

In [395]:
np.argmin(a)

7

In [399]:
a

array([76, 36, 33, 41, 60, 12, 57,  7, 23,  1, 45, 22,  7, 38, 19, 66, 38,
       34, 85, 74, 23, 27, 60, 50, 88, 53, 78, 66, 67, 33,  6, 61, 69, 77,
       46, 16, 67, 10, 67,  6, 81,  1, 16, 92,  1, 43, 41, 17, 80, 87, 15,
       72, 80, 18, 49, 57, 21, 61,  5, 72, 33,  2, 50,  3, 21,  6, 87,  8,
       32, 32, 70,  0,  6, 24,  4, 57, 97, 67, 33, 31,  9, 41, 16, 13, 89,
       54, 98,  8, 65, 41, 47, 23, 50, 73,  7, 73, 39, 90, 22, 57, 23, 53,
       48, 45, 52, 10, 69, 30,  8, 67, 30, 59, 18, 43, 98, 21, 59, 38, 73,
       11])

In [398]:
np.nonzero(a)

(array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         65,  66,  67,  68,  69,  70,  72,  73,  74,  75,  76,  77,  78,
         79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
         92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
        105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
        118, 119]),)

** Функции для работы с матрицами **

In [400]:
m

array([[1, 4, 9],
       [2, 3, 1],
       [0, 7, 6]])

In [401]:
np.diag(m)

array([1, 3, 6])

In [402]:
m.diagonal()

array([1, 3, 6])

Для целого класса функций из линейной алгебры есть свой суб-модуль np.linalg.

http://docs.scipy.org/doc/numpy/reference/routines.linalg.html

In [403]:
MM = np.random.randn(9, 6)

In [404]:
U, s, V = np.linalg.svd(MM, full_matrices=False)
U.shape, V.shape, s.shape

((9, 6), (6, 6), (6,))

In [406]:
S = np.diag(s)

In [407]:
MM - np.dot(U, np.dot(S, V))

array([[ 5.55111512e-16,  0.00000000e+00, -4.44089210e-16,
        -1.77635684e-15, -8.32667268e-16,  2.44249065e-15],
       [ 2.22044605e-16,  1.77635684e-15, -1.11022302e-15,
        -3.55271368e-15, -1.55431223e-15,  1.16573418e-15],
       [ 8.88178420e-16,  1.11022302e-15,  6.66133815e-16,
         1.11022302e-15,  9.71445147e-17,  6.10622664e-16],
       [-4.44089210e-16, -3.33066907e-16, -1.33226763e-15,
        -3.10862447e-15,  0.00000000e+00,  2.22044605e-15],
       [ 4.44089210e-16,  1.77635684e-15, -1.55431223e-15,
        -4.66293670e-15, -3.53883589e-16,  2.66453526e-15],
       [ 0.00000000e+00, -2.49800181e-16, -9.71445147e-16,
        -1.15185639e-15,  1.11022302e-15,  0.00000000e+00],
       [ 5.27355937e-16,  4.44089210e-16, -2.22044605e-16,
        -2.22044605e-16, -2.22044605e-16, -5.82867088e-16],
       [ 0.00000000e+00, -1.11022302e-15,  2.10942375e-15,
         1.77635684e-15, -1.99840144e-15, -1.05471187e-15],
       [ 4.44089210e-16, -6.66133815e-16,  1.221

In [408]:
np.allclose(MM, np.dot(U, np.dot(S, V)))

True

** Векторизация кода **

В numpy есть встроенная функция vectorize, которая "автоматически" векторизует вашу функцию:

In [411]:
def heavyside(x):
    if x >= 0:
        return 1
    else:
        return 0

In [412]:
heavyside(np.array([-3, -2, -1, 0, 1, 2, 3]))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [427]:
def heavyside(x):
    if x%2 == 0:
        return 1
    else:
        return 0

In [428]:
heavyside_vec = np.vectorize(heavyside)

In [429]:
heavyside_vec(np.array([-3, -2, -1, 0, 1, 2, 3]))

array([0, 1, 0, 1, 0, 1, 0])

Тем не менее, лучше сразу пишите так:

In [435]:
def heavyside(x):
    return 1 * (x >= 0)

In [437]:
heavyside(np.array([-3,-2,-1,0,1,2,3]))

array([0, 0, 0, 1, 1, 1, 1])

In [438]:
np.array([-3,-2,-1,0,1,2,3]) >= 0

array([False, False, False,  True,  True,  True,  True])

In [439]:
1 * (np.array([-3,-2,-1,0,1,2,3]) >= 0)

array([0, 0, 0, 1, 1, 1, 1])

** Условные выражения **

Как вы уже поняли, для вектора конструкция типа if (vector) не подходит.

In [440]:
M

matrix([[0.76420585, 0.31591944, 0.2711323 ],
        [0.23702937, 0.65843584, 0.17618727],
        [0.16543585, 0.81015897, 0.07469407]])

In [441]:
if (M > 5).any():
    print("at least one element in M is larger than 5")
else:
    print("no element in M is larger than 5")

no element in M is larger than 5


In [442]:
if (M > 5).all():
    print("all elements in M are larger than 5")
else:
    print("all elements in M are not larger than 5")

all elements in M are not larger than 5


## TLDR:
- всегда используйте встроенные в np функции;
- векторизуйте везде, где это возможно!

# 2.5. Numpy - I/O.

В данном случае у нас на выбор 2 опции - либо формат numpy, либо просто текстовый файл.

In [443]:
!ls

Black_man.txt  HW1.ipynb  matplotlib.ipynb  numpy.ipynb  pandas.ipynb


In [444]:
np.save("random.npy", M)

In [445]:
!ls

Black_man.txt  matplotlib.ipynb  pandas.ipynb
HW1.ipynb      numpy.ipynb	 random.npy


In [446]:
!cat Black_man.txt | head -9

Черный человек
Друг мой, друг мой,
Я очень и очень болен.
Сам не знаю, откуда взялась эта боль.
То ли ветер свистит
Над пустым и безлюдным полем,
То ль, как рощу в сентябрь,
Осыпает мозги алкоголь.



In [447]:
N = np.load("random.npy")

In [450]:
np.savetxt('random.csv', M, delimiter='\t')

In [451]:
! cat random.csv

7.642058535666849117e-01	3.159194385045919207e-01	2.711323037904979083e-01
2.370293728980115144e-01	6.584358371912527597e-01	1.761872653199735295e-01
1.654358461053885287e-01	8.101589729759350877e-01	7.469407136584482743e-02


In [452]:
np.loadtxt('random.csv')

array([[0.76420585, 0.31591944, 0.2711323 ],
       [0.23702937, 0.65843584, 0.17618727],
       [0.16543585, 0.81015897, 0.07469407]])

# А теперь задачки!

In [454]:
(np.arange(100))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [453]:
(lambda x: x + 1)(np.arange(100))

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [459]:
lambda x, y: x + y

<function __main__.<lambda>(x, y)>

In [456]:
_(1, 2)

3

In [460]:
lambda x, y: x * y

<function __main__.<lambda>(x, y)>

In [461]:
_(1, 2)

2

#### Написать функцию, которая поможет развернуть все слова в строке:

In [463]:
s = "Hello world"

In [468]:
s

'Hello world'

In [471]:
a = ["dss", "dfdfad"]

In [478]:
" ".join(a)

'dss dfdfad'

In [470]:
" ".join(s[::-1].split()[::-1])

'olleH dlrow'

In [ ]:
def reverser(string):
    return 

In [480]:
x = 12132324

#### Написать функцию, которая определяет является ли число палиндромом

In [483]:
def is_palindrom(x):
    return str(x) == str(x)[::-1]

In [486]:
is_palindrom(12321)

True

#### Сложите цифры целого числа

In [488]:
a = 126567654

In [498]:
sum(map(int, list(str(a))))

42

In [500]:
np.array(list(str(a))).astype(int).sum()

42

#### Извлеките из массива числа, делимые на 15.

In [502]:
nums = np.array([45, 55, 60, 37, 100, 105, 220])

#### Напишите программу, которая принимает текст и выводит два слова: наиболее часто встречающееся и самое длинное.

In [506]:
with open('./Black_man.txt') as f:
    black = f.readlines()

In [507]:
lower = (" ".join(black).lower())

In [508]:
only_letters = ""
for i in lower:
    if (i >= "а" and i <= "я") or i in [" ", "\n"]:
        only_letters += i

In [511]:
x = only_letters.split()

In [514]:
l = [len(i) for i in x]

In [519]:
np.array(x)[np.argsort(l)[:5]]

array(['в', 'в', 'а', 'с', 'в'], dtype='<U14')

#### Напишите функцию, которая создаёт комбинацию двух списков таким образом:

[1, 2, 3] (+) [11, 22, 33] -> [1, 11, 2, 22, 3, 33]

In [543]:
x = [1, 2, 3, -1, -1]
y = [11, 22, 33, 1123]

In [544]:
a = np.zeros(len(x) + len(y))

In [545]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [547]:
a[0::2] = x
a[1::2] = y

In [548]:
a.astype(int)

array([   1,   11,    2,   22,    3,   33,   -1, 1123,   -1])

#### Написать функцию, которая удаляет лишние пробелы в строке

In [550]:
x = "I   Love        Python"

In [551]:
def delete_spaces(string):
    return " ".join(x.split())

In [552]:
delete_spaces(x)

'I Love Python'

In [ ]:
%timeit delete_spaces_optimal(lower)

In [ ]:
%timeit delete_spaces(lower)